/*
 * Created by Vraj Contractor
 */

package com.movieexplorer.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * Entity class representing user feedback submitted via the app.
 * Maps to a database table for persistence.
 */
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Feedback {

    // Primary key, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Name of the user submitting feedback
    private String userName;

    // Email of the user submitting feedback
    private String userEmail;

    // Feedback message content
    private String message;

    // Note: You can extend this class to include fields like movieTitle, comment, or rating
    // if you want to associate feedback with a particular movie.
}
